module.exports = {
  DreamProductCategories: [
    {
      id: 1,
      name: "Bajaj Services (More Rewarding)",
      key: "bajaj-services",
      products: [
        {
          id: 1,
          name: "Cards",
          key: "cards",
          image: "/ProductImages/card.png",
          investAmount:17000,
        },
        {
          id: 2,
          name: "Insurance",
          key: "insurance",
          image: "/ProductImages/insurance.png",
          investAmount:17000,
        },
        {
          id: 3,
          name: "Loans",
          key: "loans",
          image: "/ProductImages/Loan.png",
          investAmount:17000,
        },
      ],
    },
    {
      id: 2,
      name: "Audio Device",
      key: "audio-device",
      products: [
        {
          id: 1,
          name: "AirPods",
          key: "airpods",
          image: "/ProductImages/AirPods.png",
          investAmount:5000,
        },
        {
          id: 2,
          name: "AirPods Pro",
          key: "airpods-pro",
          image: "/ProductImages/Airpods-pro.png",
          investAmount:6500,
        },
        {
          id: 3,
          name: "Sony XMH5",
          key: "sony-xmh5",
          image: "/ProductImages/SOny-xmh3.png",
          investAmount:6000,
        },
        {
          id: 4,
          name: "OnePlus Buds",
          key: "oneplus-buds",
          image: "/ProductImages/oneplus-buds.png",
          investAmount:3000,
        },
        {
          id: 5,
          name: "Nothing Ear(2)",
          key: "nothing-ear(2)",
          image: "/ProductImages/nothingear2.png",
          investAmount:2500,
        },
        {
          id: 6,
          name: "Google Pixel Buds",
          key: "google-pixel-buds",
          image: "/ProductImages/pixelbuds.png",
          investAmount:2500,
        },
      ],
    },
    {
      id: 3,
      name: "Wearables",
      key: "wearables",
      products: [
        {
          id: 1,
          name: "Amazfit GTR4",
          key: "amazfit-gtr4",
          image: "/ProductImages/amazfitgtr4.png",
          investAmount:4000,
        },
        {
          id: 2,
          name: "Apple Watch",
          key: "apple-watch",
          image: "/ProductImages/Apple-watch.png",
          investAmount:11000,
        },
        {
          id: 3,
          name: "OnePlus Watch",
          key: "oneplus-watch",
          image: "/ProductImages/oneplus-watch.png",
          investAmount:3500,
        },
        {
          id: 4,
          name: "Samsung Galaxy Watch 5",
          key: "samsung-galaxy-watch5",
          image: "/ProductImages/samsung-watch5.png",
          investAmount:8000,
        },
        {
          id: 5,
          name: "Samsung Galaxy Watch 5 Pro",
          key: "samsung-galaxy-watch-5-Pro",
          image: "/ProductImages/samsungwatch5pro.png",
          investAmount:12000,
        },
        {
          id: 6,
          name: "Apple Watch Ultra",
          key: "watch-ultra.png",
          image: "/ProductImages/Apple-watch.png",
          investAmount:21000,
        },
      ],
    },
    {
      id: 4,
      name: "Smartphones",
      key: "smartphones",
      products: [
        {
          id: 1,
          name: "iPhone 13",
          key: "iphone-13",
          image: "/ProductImages/iphone12.png",
          investAmount:15000,
        },
        {
          id: 2,
          name: "Samsung Galaxy S22",
          key: "samsung-galaxy-s22",
          image: "/ProductImages/samsungs21.png",
          investAmount:18000,
        },
        {
          id: 3,
          name: "OnePlus 11",
          key: "oneplus-11",
          image: "/ProductImages/oneplus11.png",
          investAmount:14000,
        },
        {
          id: 4,
          name: "Google Pixel 7",
          key: "google-pixel-7",
          image: "/ProductImages/pixel7.png",
          investAmount:12000,
        },
        {
          id: 5,
          name: "iPhone 14",
          key: "iphone-14",
          image: "/ProductImages/iphone14.png",
          investAmount:16000,
        },
        {
          id: 6,
          name: "Samsung Z Flip",
          key: "samsung-z-flip",
          image: "/ProductImages/zflip.png",
          investAmount:16000,
        },
      ],
    },
  ],
  MonetaryRewardsList: [
    {
      id: 1,
      key: "off100",
      name: "Extra ₹100 off",
      tier: "Bronze",
    },
    {
      id: 2,
      key: "off5percent",
      name: "Extra 5% off",
      tier: "Silver",
    },
    {
      id: 3,
      key: "off10percent",
      name: "Extra 10% off",
      tier: "Gold",
    },
    {
      id: 4,
      key: "off1000",
      name: "Extra ₹1000 off",
      tier: "Diamond",
    },
    {
      id: 5,
      key: "off15percent",
      name: "Extra 15% off",
      tier: "Elite",
    },
  ],
  NonMonetaryRewardsList: [
    {
      id: 1,
      key: "off100",
      name: "Extra ₹100 off",
      tier: "Bronze",
    },
    {
      id: 2,
      key: "off5percent",
      name: "Extra 5% off",
      tier: "Silver",
    },
    {
      id: 3,
      key: "off10percent",
      name: "Extra 10% off",
      tier: "Gold",
    },
    {
      id: 4,
      key: "off1000",
      name: "Extra ₹1000 off",
      tier: "Diamond",
    },
    {
      id: 5,
      key: "off15percent",
      name: "Extra 15% off",
      tier: "Elite",
    },
  ],
  TiersList: [
    {
      id: 1,
      key: "Bronze",
      name: "Bronze Saver",
      tokenStart: 0,
      tokenEnd: 1000,
      amountRatio: 0.03,
      image: "/Tiers/bronze.png",
    },
    {
      id: 2,
      key: "Silver",
      name: "Silver Saver",
      tokenStart: 1001,
      tokenEnd: 6000,
      amountRatio: 0.05,
      image: "/Tiers/silver.png",
    },
    {
      id: 3,
      key: "Gold",
      name: "Gold Saver",
      tokenStart: 6001,
      tokenEnd: 15000,
      amountRatio: 0.06,
      image: "/Tiers/gold.png",
    },
    {
      id: 4,
      key: "Diamond",
      name: "Diamond Saver",
      tokenStart: 15001,
      tokenEnd: 25000,
      amountRatio: 0.07,
      image: "/Tiers/diamond.png",
    },
    {
      id: 5,
      key: "Elite",
      name: "Elite Saver",
      tokenStart: 25000,
      tokenEnd: 50000,
      amountRatio: 0.08,
      image: "/Tiers/elite.png",
    },
  ],
  TransactionCategories: [
    {
      id: 1,
      name: "Food",
      key: "food",
      color: "#FF0000",
    },
    {
      id: 2,
      name: "Transport",
      key: "transport",
      color: "#FFA500",
    },
    {
      id: 3,
      name: "Rent",
      key: "rent",
      color: "#FFFF00",
    },
    {
      id: 4,
      name: "Installment",
      key: "installment",
      color: "#00FF00",
    },
    {
      id: 5,
      name: "Electronics",
      key: "electronics",
      color: "#0000FF",
    },
    {
      id: 6,
      name: "Others",
      key: "others",
      color: "#4B0082",
    },
  ],
};
